#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Support for Python is experimental, and requires building SNAPSHOT image of Apache Spark,
# with `imagePullPolicy` set to Always

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark-custom:3.5.0
  imagePullPolicy: Never
  mainClass: com.github.fescalhao.spark_project.Main
  mainApplicationFile: "local:///tmp/spark_apps/spark_project_3.5.0_0.1.0.jar"
  sparkVersion: "3.5.0"
  volumes:
    - name: "spark-apps"
      persistentVolumeClaim:
        claimName: spark-apps-pvc
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: local-airflow-worker
    volumeMounts:
      - name: "spark-apps"
        mountPath: "/tmp/spark_apps"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
    volumeMounts:
      - name: "spark-apps"
        mountPath: "/tmp/spark_apps"
  arguments:
    - "--project"
    - "movies"
    - "--layer"
    - "silver"
    - "--entity"
    - "ratings"
    - "--aws_user_access_key"
    - "AKIA2VQHSKWUUU3TFMFD"
    - "--aws_user_secret_key"
    - "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"
    - "--aws_assume_role_arn"
    - "arn:aws:iam::733381547433:role/MoviesProjectRole"
  timeToLiveSeconds: 120