apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/docker/airflow/dags
  storageClassName: "standard"
  claimRef:
    namespace: default
    name: airflow-dags-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/docker/airflow/logs
  storageClassName: "standard"
  claimRef:
    namespace: default
    name: airflow-logs-pvc