apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-apps-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/docker/spark/spark_apps
  storageClassName: "standard"
  claimRef:
    namespace: default
    name: spark-apps-pvc