apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark-custom:3.5.0
  imagePullPolicy: Never
  mainClass: com.github.fescalhao.spark_project.Main
  mainApplicationFile: "local:///tmp/spark_apps/spark_project_3.5.0_0.1.0.jar"
  sparkVersion: "3.5.0"
  volumes:
    - name: "spark-apps"
      persistentVolumeClaim:
        claimName: spark-apps-pvc
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: local-airflow-worker
    volumeMounts:
      - name: "spark-apps"
        mountPath: "/tmp/spark_apps"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
    volumeMounts:
      - name: "spark-apps"
        mountPath: "/tmp/spark_apps"
  arguments:
  timeToLiveSeconds: 120